version: 2.1

orbs:
  telemetry_registry:
    executors:
      elixir:
        parameters:
          elixir:
            description: Elixir version to used by the job
            type: string
          otp:
            description: OTP release to used by the job
            type: string
        docker:
          - image: arkgil/alpine-elixir:<<parameters.elixir>>-otp-<<parameters.otp>>
    orbs:
      rebar3: tsloughter/rebar3@0.6.3
      codecov: codecov/codecov@1.0.4

    jobs:
      build_and_test_erlang:
        parameters:
          version:
            description: The Erlang/OTP docker image tag to use.
            type: string
        executor:
          name: rebar3/erlang
          tag: <<parameters.version>>
        steps:
          - checkout
          - rebar3/with_deps_cache:
              cache_key_postfix: -<<parameters.version>>
              steps:
                - rebar3/compile
                - rebar3/dialyzer
                - rebar3/xref
                - rebar3/ct

      build_and_test_elixir:
        parameters:
          elixir:
            description: Elixir version to used by the job
            type: string
          otp:
            description: OTP release to used by the job
            type: string
          codecov_flag:
            description: String the coverage reports are grouped by
            type: string
        executor:
          name: elixir
          elixir: <<parameters.elixir>>
          otp: <<parameters.otp>>
        steps:
          - run: mix local.hex --force
          - run: mix local.rebar --force
          - checkout
          - run: mix deps.get
          - run: mix test
    
workflows:
  build_and_test_erlang:
    jobs:
      - telemetry_registry/build_and_test_erlang:
          name: "otp-22"
          version: "22"
      - telemetry_registry/build_and_test_erlang:
          name: "otp-21"
          version: "21"

  build_and_test_elixir:
    jobs:
      - telemetry_registry/build_and_test_elixir:
          name: "1.10-otp-22"
          elixir: "1.10.0"
          otp: "22"
          codecov_flag: "1_10_otp22"
      - telemetry_registry/build_and_test_elixir:
          name: "1.10-otp-21"
          elixir: "1.10.0"
          otp: "21"
          codecov_flag: "1_10_otp21"
      - telemetry_registry/build_and_test_elixir:
          name: "1.6-otp-21"
          elixir: "1.6.6"
          otp: "21"
          codecov_flag: "1_6_otp21"
      - telemetry_registry/build_and_test_elixir:
          name: "1.6-otp-19"
          elixir: "1.6.6"
          otp: "19"
          codecov_flag: "1_6_otp19"
