name: Elixir

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on ${{ matrix.elixir }} OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - otp_version: "25.2"
            elixir_version: "1.14.4"
            os: ubuntu-22.04
          - otp_version: "22.3"
            elixir_version: "22.3"
            os: ubuntu-20.04
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: ${{ matrix.elixir }}
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
          deps
        key: ${{ runner.os }}-build-elixir-${{ matrix.elixir }}-${{ matrix.otp_version }}-${{ hashFiles(format('mix.lock')) }}-1
        restore-keys: |
          ${{ runner.os }}-build-elixir-${{ matrix.elixir }}-${{ matrix.otp_version }}-1-
    - name: Deps
      run: mix deps.get
    - name: Compile
      run: mix compile
    - name: Format
      run: mix format
    - name: Common Test tests
      run: mix test
#  dialyzer:
#    name: Dialyze on ${{ matrix.elixir }} OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        otp_version: ['23.2.1', '21.3.8.17']
#        elixir: ['1.10.4', '1.11.3']
#        os: [ubuntu-latest]
#    steps:
#    - uses: actions/checkout@v2
#    - uses: erlef/setup-elixir@v1
#      with:
#        otp-version: ${{ matrix.otp_version }}
#        elixir-version: ${{ matrix.elixir }}
#    - uses: actions/cache@v2
#      name: Cache
#      with:
#        path: |
#          _build
#          deps
#        key: ${{ runner.os }}-dialyzer-${{ matrix.elixir }}-${{ matrix.otp_version }}-${{ hashFiles('mix.lock') }}-1
#        restore-keys: |
#          ${{ runner.os }}-dialyzer-${{ matrix.elixir }}-${{ matrix.otp_version }}-1-
#    - name: Deps
#      run: mix deps.get
#    - name: Dialyzer
#      run: mix dialyzer
