name: Elixir

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['23.2.1', '21.3.8.17']
        elixir: ['1.10.4', '1.11.3']
        os: [ubuntu-latest]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp_version }}
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-elixir-${{ matrix.otp_version }}-${{ hashFiles(format('mix.lock')) }}-1
        restore-keys: |
          ${{ runner.os }}-build-elixir-${{ matrix.otp_version }}-1-
    - name: Compile
      run: mix compile
    - name: Format
      run: mix format
    - name: Common Test tests
      run: mix test
  dialyzer:
    name: Dialyze on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['23.2.1', '21.3.8.17']
        elixir: ['1.10.4', '1.11.3']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp_version }}
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-dialyzer-${{ matrix.otp_version }}-${{ hashFiles('mix.lock') }}-1
        restore-keys: |
          ${{ runner.os }}-dialyzer-${{ matrix.otp_version }}-1-
    - name: Dialyzer
      run: mix dialyzer
