name: Erlang

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rebar3_version: ["3.20.0"]
        include:
          - otp_version: "23.3.4.18"
            rebar3_version: "3.20.0"
          - otp_version: "22.3.4.26"
            rebar3_version: "3.18.0"
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-erlang-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-1
        restore-keys: |
          ${{ runner.os }}-build-erlang-${{ matrix.otp_version }}-1-
    - name: Compile
      run: rebar3 compile
    - name: Common Test tests
      run: rebar3 ct --cover
    - name: XRef
      run: rebar3 xref
